"""Adds default role

Revision ID: b494f6f6a4da
Revises: a3c553bf942d
Create Date: 2024-08-19 02:32:32.175754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b494f6f6a4da'
down_revision = 'a3c553bf942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index('ix_parcels_tracking_number')
        batch_op.create_index(batch_op.f('ix_parcels_tracking_number'), ['tracking_number'], unique=True)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipients_email')
        batch_op.create_index(batch_op.f('ix_recipients_email'), ['email'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipients_email'))
        batch_op.create_index('ix_recipients_email', ['email'], unique=False)

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcels_tracking_number'))
        batch_op.create_index('ix_parcels_tracking_number', ['tracking_number'], unique=True)

    # ### end Alembic commands ###
