DEF READ_AND_MODIFY_FILE():
    FILENAME = INPUT("ENTER THE FILENAME TO READ FROM: ")

    TRY:
        WITH OPEN(FILENAME, "R") AS INFILE:
            CONTENT = INFILE.READ()

        # MODIFY CONTENT (E.G., CONVERT TO UPPERCASE)
        MODIFIED_CONTENT = CONTENT.UPPER()

        NEW_FILENAME = "MODIFIED_" + FILENAME
        WITH OPEN(NEW_FILENAME, "W") AS OUTFILE:
            OUTFILE.WRITE(MODIFIED_CONTENT)

        PRINT(F"MODIFIED CONTENT WRITTEN TO '{NEW_FILENAME}'.")

    EXCEPT FILENOTFOUNDERROR:
        PRINT("❌ ERROR: FILE NOT FOUND.")
    EXCEPT IOERROR:
        PRINT("❌ ERROR: FILE CAN'T BE READ OR WRITTEN.")
    EXCEPT EXCEPTION AS E:
        PRINT(F"❌ UNEXPECTED ERROR: {E}")


# RUN THE FUNCTION
READ_AND_MODIFY_FILE()
